openapi: 3.0.0
info:
  title: Hotel Services API
  description: API que proporciona los servicios disponibles por hotel para una lista de IDs de hoteles.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Servidor local
paths:
  /hotels/services/{hotelIds}:
    get:
      summary: Obtener los servicios de los hoteles
      description: Retorna la lista de hoteles con sus servicios según los IDs de los hoteles proporcionados.
      parameters:
        - name: hotelIds
          in: path
          required: true
          schema:
            type: string
            example: "1,2,3"
      responses:
        '200':
          description: Lista de hoteles con servicios
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    hotelId:
                      type: integer
                      example: 1
                    hotelName:
                      type: string
                      example: Hotel California
                    services:
                      type: array
                      items:
                        type: object
                        properties:
                          serviceId:
                            type: integer
                            example: 3
                          serviceName:
                            type: string
                            example: Aire acondicionado
        '404':
          description: No se encontraron registros
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 404
                  description:
                    type: string
                    example: No se encontraron registros
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 500
                  description:
                    type: string
                    example: error de servidor
